# Site settings
#FROM Documentation Bootstrap Site
title: Suker's Blog 
email: kchhero@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://kchhero.github.io" # the base hostname & protocol for your site
twitter_username: 
github_username:  kchhero

safe: true
lsi: false


# Build settings
markdown: kramdown


collections:
  test_collection:
    navmenu: navmenu_testcollection
    output: true


defaults:

  - # Global default is use structures in /_data/toc.yml and /_data/navmenu.yml
    scope:
      path: ""

    values:
      toc: bigtoc
      navmenu: navmenu

