# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: rouge
markdown: kramdown
disqus: kchhero
google_analytics: kchhero
title: suker

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: SUKER HOME

description: Stylish Jekyll Theme
author:
  name: kchhero
  email: kchhero@gmail.com
  github: kchhero
  linkedin: kchhero
  bio: If you do not act, there is no change.
  gravatar: https://s.gravatar.com/avatar/fdd3f88092f0e74ee242029c870349ed?s=80
  email_md5: fdd3f88092f0e74ee242029c870349ed

rss_path: feed.xml
about_path: about.html
tags_path: tags.html

# set it as url of an image
# sidebar_background_image: https://www.dropbox.com/s/g9h23zrycedxtk5/sky.png?raw=1

BASE_PATH:

gems:
  - jekyll-paginate
